image: "python:3.10"

before_script:
  - python --version

after_script:
  - docker-compose down -v

stages:
  - lint
  - security

lint:
  stage: lint
  before_script:
    - pip3 install flake8
  script:
  - flake8 .
  allow_failure: true

.anchore_scan:
  image: anchore/engine-cli:latest
  stage: security
  tags:
    - docker-privileged
  variables:
    # Configure for recursive submodule cloning
    GIT_SUBMODULE_STRATEGY: recursive


