version: '3.7'

services:
  db:
    image: postgres:12.3-alpine
    # uncomment the following for local development
    # to allow you to access the DB at 127.0.0.1:55432
    # ports:
    #  - 55432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres

  test:
    image: test_gnota_backend:latest
    build:
      context: .
      dockerfile: Dockerfile.tests
    container_name: skp_tests
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    command: |-
        sh -c '
        cd skpapps
        python manage.py test
        '
