# Generated by Django 4.1.2 on 2022-12-03 03:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurations",
            name="batas_input",
            field=models.DateField(
                default=django.utils.timezone.now,
                help_text="Batas Pengisian SKP",
                null=True,
                verbose_name="Batas Pengisian",
            ),
        ),
    ]
