# Generated by Django 4.1.2 on 2022-12-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_configurations_batas_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurations",
            name="sipo_password",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SIPO Password API"
            ),
        ),
        migrations.AddField(
            model_name="configurations",
            name="sipo_username",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="SIPO Username API"
            ),
        ),
    ]
