# Generated by Django 4.1.2 on 2022-12-07 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_configurations_sipo_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configurations",
            name="sipo_token",
            field=models.TextField(
                blank=True, null=True, verbose_name="SIPO Token API"
            ),
        ),
    ]
