# Generated by Django 4.1.2 on 2022-12-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_configurations_presensi_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "jenis_task",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Sinkron Pegawai Presensi"),
                            (2, "Sinkron Pegawai SIPO by NIP"),
                        ],
                        null=True,
                        verbose_name="Jenis Task",
                    ),
                ),
                (
                    "presentase",
                    models.FloatField(blank=True, null=True, verbose_name="Presentase"),
                ),
                ("is_done", models.BooleanField(default=False, verbose_name="Selesai")),
            ],
            options={
                "verbose_name": "Task List",
                "verbose_name_plural": "Task List",
            },
        ),
    ]
