# Generated by Django 4.1.2 on 2022-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_tasklist"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasklist",
            name="parameter",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Parameter"
            ),
        ),
    ]
