# Generated by Django 4.1.2 on 2022-12-12 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_tasklist_parameter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="configurations",
            name="presensi_token",
        ),
    ]
