# Generated by Django 4.1.2 on 2022-11-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0002_unitkerja_account_eselon_account_golongan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="jenis_jabatan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("JPT", "Jabatan Pimpinan Tinggi"),
                    ("JF", "Jabatan Fungsional"),
                    ("JA", "Jabatan Administrator"),
                ],
                max_length=5,
                null=True,
                verbose_name="Jenis Jabatan",
            ),
        ),
    ]
