# Generated by Django 4.1.2 on 2022-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0004_account_atasan"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="tangggal_nonaktif",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tanggal Nonaktif"
            ),
        ),
    ]
