# Generated by Django 4.1.2 on 2022-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0005_account_tangggal_nonaktif"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitkerja",
            name="aktif",
            field=models.BooleanField(default=True),
        ),
    ]
