# Generated by Django 4.1.2 on 2022-12-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0006_unitkerja_aktif"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="id_sipo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID SIPO"
            ),
        ),
        migrations.AddField(
            model_name="unitkerja",
            name="id_sipo",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="ID SIPO"
            ),
        ),
    ]
