# Generated by Django 4.1.2 on 2023-01-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0007_account_id_sipo_unitkerja_id_sipo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="golongan",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I/A", "I/a"),
                    ("I/B", "I/b"),
                    ("I/C", "I/c"),
                    ("I/D", "I/d"),
                    ("II/A", "II/a"),
                    ("II/B", "II/b"),
                    ("II/C", "II/c"),
                    ("II/D", "II/d"),
                    ("III/A", "III/a"),
                    ("III/B", "III/b"),
                    ("III/C", "III/c"),
                    ("III/D", "III/d"),
                    ("IV/A", "IV/a"),
                    ("IV/B", "IV/b"),
                    ("IV/C", "IV/c"),
                    ("IV/D", "IV/d"),
                    ("IV/E", "IV/e"),
                ],
                max_length=6,
                null=True,
                verbose_name="Golongan",
            ),
        ),
    ]
