# Generated by Django 4.1.2 on 2023-01-05 08:54

from django.db import migrations, models

import usom.utils


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0008_alter_account_golongan"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="foto",
            field=models.ImageField(
                blank=True,
                max_length=255,
                null=True,
                upload_to=usom.utils.PathForFileModel("foto/"),
            ),
        ),
    ]
