# Generated by Django 4.1.2 on 2022-12-26 06:32

from django.contrib.auth.models import Group, Permission
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    print('forwards')
    base_list = [
        'add_sasarankinerja',
        'view_sasarankinerja'
    ]
    obj, created = Group.objects.get_or_create(name="Input")
    if created:
        obj.permissions.add(*list(Permission.objects.filter(codename__in=base_list).values_list('id', flat=True)))
        obj.save()

    base_list += [
        'view_account',
        'view_unitkerja',
    ]

    obj_penilai, created_penilai = Group.objects.get_or_create(name="Penilai")
    if created_penilai:
        obj_penilai.permissions.add(*list(Permission.objects.filter(codename__in=base_list).values_list('id', flat=True)))
        obj_penilai.save()

    obj_bupati, created_bupati = Group.objects.get_or_create(name="Bupati")
    if created_bupati:
        obj_bupati.permissions.add(*list(Permission.objects.filter(codename__in=base_list).values_list('id', flat=True)))
        obj_bupati.save()

def reverse_func(apps, schema_editor):
    print('reverse')

class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0008_alter_account_golongan"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func, elidable=False),
    ]
