# Generated by Django 4.1.2 on 2022-12-26 06:32

from django.contrib.auth.models import Group, Permission
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    print('forwards')
    base_list = [
        'add_sasarankinerja',
        'view_sasarankinerja',
        'change_sasarankinerja',
        'delete_sasarankinerja',
    ]
    obj, created = Group.objects.get_or_create(name="Input")
    if created:
        pass
    else:
        obj.permissions.clear()
    obj.permissions.add(*list(Permission.objects.filter(codename__in=base_list).values_list('id', flat=True)))
    obj.save()

def reverse_func(apps, schema_editor):
    print('reverse')

class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0009_initial_bupati_permission"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func, elidable=False),
    ]
