# Generated by Django 4.1.2 on 2023-01-10 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0009_account_foto"),
        ("usom", "0010_add_input_permission"),
    ]

    operations = []
