# Generated by Django 4.1.2 on 2023-01-11 04:19

from django.db import migrations, models

from usom.models import Golongan
from usom.utils import angka_golongan, roman_to_int


def forwards_func(apps, schema_editor):
    print('forwards')
    GOLONGAN = [
        "I/a",
        "I/b",
        "I/c",
        "I/d",
        "II/a",
        "II/b",
        "II/c",
        "II/d",
        "III/a",
        "III/b",
        "III/c",
        "III/d",
        "IV/a",
        "IV/b",
        "IV/c",
        "IV/d",
        "IV/e",
    ]
    for item in GOLONGAN:
        split = item.split("/")
        angka = split[0]
        huruf = split[1]
        kode_angka = "{}{}".format(
            roman_to_int(angka),
            angka_golongan(huruf)
        )
        
        obj, created = Golongan.objects.get_or_create(
            kode_angka=kode_angka,
            angka=roman_to_int(angka),
            huruf=huruf
        )
        obj.save()

def reverse_func(apps, schema_editor):
    print('reverse')

class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0011_merge_0009_0010_migrations"),
    ]

    operations = [
        migrations.CreateModel(
            name="Golongan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kode",
                    models.CharField(max_length=100, null=True, verbose_name="Kode"),
                ),
                (
                    "kode_angka",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Kode Angka"
                    ),
                ),
                (
                    "angka",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3),(4, 4)],
                        db_index=True,
                        verbose_name="Angka",
                    ),
                ),
                (
                    "huruf",
                    models.CharField(
                        choices=[
                            ("a", "a"),
                            ("b", "b"),
                            ("c", "c"),
                            ("d", "d"),
                            ("e", "e"),
                        ],
                        db_index=True,
                        max_length=2,
                        verbose_name="Huruf",
                    ),
                ),
                (
                    "keterangan",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keterangan"
                    ),
                ),
            ],
            options={
                "verbose_name": "Golongan",
                "verbose_name_plural": "Golongan",
                "ordering": ["angka", "huruf"],
            },
        ),
        migrations.RunPython(forwards_func, reverse_func, elidable=False),
    ]
