# Generated by Django 4.1.2 on 2023-01-11 04:54

import django.db.models.deletion
from django.db import migrations, models

from usom.models import Account, Golongan


def forwards_func(apps, schema_editor):
    print('forwards')
    for i in Account.objects.filter(golongan__isnull=False):
        golongan = i.golongan.split('/')
        golongan = "{}/{}".format(golongan[0],golongan[1].lower())
        find_ = Golongan.objects.filter(kode=golongan)
        if find_.exists():
            obj = find_.last()
            i.golongan_fk = obj
            i.save()


def reverse_func(apps, schema_editor):
    print('reverse')

class Migration(migrations.Migration):
    
    dependencies = [
        ("usom", "0012_golongan"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="golongan_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="usom.golongan",
            ),
        ),
        migrations.RunPython(forwards_func, reverse_func, elidable=False),
    ]
