# Generated by Django 4.1.2 on 2023-01-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    
    dependencies = [
        ("usom", "0013_alter_account_golongan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="account",
            name="golongan"
        ),
        migrations.RenameField(
            model_name="account",
            old_name="golongan_fk",
            new_name="golongan",
        )
    ]
