# Generated by Django 4.1.2 on 2023-01-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0014_rename_golongan"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="status_pegawai",
            field=models.CharField(
                blank=True,
                choices=[("ASN", "ASN"), ("NON", "NON ASN")],
                max_length=50,
                null=True,
                verbose_name="Status Pegawai",
            ),
        ),
    ]
