# Generated by Django 4.1.2 on 2022-11-02 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("usom", "0002_unitkerja_account_eselon_account_golongan_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SasaranKinerja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unor_text",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Unor Text",
                    ),
                ),
                (
                    "jabatan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Jabatan",
                    ),
                ),
                (
                    "periode_awal",
                    models.DateField(null=True, verbose_name="Periode Awal"),
                ),
                (
                    "periode_akhir",
                    models.DateField(null=True, verbose_name="Periode Akhir"),
                ),
                (
                    "pendekatan",
                    models.IntegerField(
                        choices=[(1, "Kuantitatif"), (2, "Kualitatif")],
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Draft"), (2, "ACTIVE")], null=True
                    ),
                ),
                (
                    "keterangan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Keterangan",
                    ),
                ),
                (
                    "pegawai",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pejabat_penilai",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pejabat_penilai_set",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "unor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usom.unitkerja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sasaran Kinerja Pegawai",
            },
        ),
    ]
