# Generated by Django 4.1.2 on 2022-11-02 05:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usom", "0002_unitkerja_account_eselon_account_golongan_and_more"),
        ("skp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sasarankinerja",
            options={
                "verbose_name": "Sasaran Kinerja Pegawai",
                "verbose_name_plural": "Sasaran Kinerja Pegawai",
            },
        ),
        migrations.AddField(
            model_name="sasarankinerja",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RencanaHasilKerja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rencana_kerja",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Rencana Hasil Kerja",
                    ),
                ),
                (
                    "penugasan_dari",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Penugasan Dari",
                    ),
                ),
                (
                    "jenis",
                    models.IntegerField(
                        choices=[(1, "Utama"), (2, "Tambahan")],
                        verbose_name="Jenis Rencana Hasik Kerja",
                    ),
                ),
                (
                    "klasifikasi",
                    models.IntegerField(
                        choices=[(1, "Organisasi"), (2, "Individu")],
                        verbose_name="Klasifikasi Rencana Hasil Kerja",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "skp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                        verbose_name="Sasaran Kinerja Pegawai",
                    ),
                ),
                (
                    "unor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="usom.unitkerja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rencana Hasil Kerja",
                "verbose_name_plural": "Rencana Hasil Kerja",
            },
        ),
        migrations.CreateModel(
            name="DetailSasaranKinerja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_pegawai",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nama Pegawai",
                    ),
                ),
                (
                    "nip_pegawai",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="NIP Pegawai",
                    ),
                ),
                (
                    "golongan_pegawai",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Pangkat Golongan Pegawai",
                    ),
                ),
                (
                    "jabatan_pegawai",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Jabatan Pegawai",
                    ),
                ),
                (
                    "unor_pegawai",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Unor Pegawai",
                    ),
                ),
                (
                    "nama_pejabat",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Nama Pejabat",
                    ),
                ),
                (
                    "nip_pejabat",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="NIP Pejabat",
                    ),
                ),
                (
                    "golongan_pejabat",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Pangkat Golongan Pejabat",
                    ),
                ),
                (
                    "jabatan_pejabat",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Jabatan Pejabat",
                    ),
                ),
                (
                    "unor_pejabat",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Unor Pejabat",
                    ),
                ),
                (
                    "skp",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detail Sasaran Kinerja",
                "verbose_name_plural": "Detail Sasaran Kinerja",
            },
        ),
    ]
