# Generated by Django 4.1.2 on 2022-11-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0003_lampiran_perilakukerja_perspektif_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lampiran",
            name="lampiran",
            field=models.CharField(default=1, max_length=200, verbose_name="Lampiran"),
            preserve_default=False,
        ),
    ]
