# Generated by Django 4.1.2 on 2022-11-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0004_lampiran_lampiran"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sasarankinerja",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Pengajuan"),
                    (3, "Persetujuan"),
                    (4, "Close"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
