# Generated by Django 4.1.2 on 2022-11-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0006_rencanahasilkerja_induk_sasarankinerja_jenis_jabatan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rencanahasilkerja",
            name="jenis",
            field=models.IntegerField(
                choices=[(1, "Utama"), (2, "Tambahan")],
                verbose_name="Jenis Rencana Hasil Kerja",
            ),
        ),
    ]
