# Generated by Django 4.1.2 on 2022-11-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0007_alter_rencanahasilkerja_jenis"),
    ]

    operations = [
        migrations.AddField(
            model_name="rencanahasilkerja",
            name="ekinerja_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Ekinerja ID"
            ),
        ),
    ]
