# Generated by Django 4.1.2 on 2022-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0008_rencanahasilkerja_ekinerja_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="rencanahasilkerja",
            name="aspek",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Aspek"
            ),
        ),
    ]
