# Generated by Django 4.1.2 on 2022-11-22 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0011_indikatorkinerjaindividu_aspek"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indikatorkinerjaindividu",
            name="rencana_kerja",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="skp.rencanahasilkerja",
                verbose_name="Rencana Hasil Kerja",
            ),
        ),
    ]
