# Generated by Django 4.1.2 on 2022-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0013_indikatorkinerjaindividu_skp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perilakukerja",
            name="status",
        ),
        migrations.AddField(
            model_name="perilakukerja",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="sasarankinerja",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "Draft"),
                    (2, "Pengajuan"),
                    (3, "Persetujuan"),
                    (4, "Close"),
                    (5, "Archive"),
                ],
                default=1,
                null=True,
            ),
        ),
    ]
