# Generated by Django 4.1.2 on 2022-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0014_remove_perilakukerja_status_perilakukerja_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="daftarperilakukerja",
            name="status",
        ),
        migrations.AddField(
            model_name="daftarperilakukerja",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
