# Generated by Django 4.1.2 on 2022-11-29 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0015_remove_daftarperilakukerja_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="daftarlampiran",
            name="skp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="skp.sasarankinerja",
                verbose_name="Sasaran Kinerja Pegawai",
            ),
        ),
    ]
