# Generated by Django 4.1.2 on 2022-12-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0016_daftarlampiran_skp"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaftarPerilakuKerjaPegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "isi",
                    models.TextField(
                        blank=True, null=True, verbose_name="Isi Ekspetasi"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "perilaku_kerja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.perilakukerja",
                        verbose_name="Perilaku Kerja",
                    ),
                ),
                (
                    "skp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                        verbose_name="Sasaran Kinerja Pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daftar Perilaku Kerja Pegawai",
                "verbose_name_plural": "Daftar Perilaku Kerja Pegawai",
            },
        ),
    ]
