# Generated by Django 4.1.2 on 2022-12-05 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0017_daftarperilakukerjapegawai"),
    ]

    operations = [
        migrations.CreateModel(
            name="RencanaAksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periode",
                    models.IntegerField(
                        choices=[
                            (1, "Januari"),
                            (2, "Februari"),
                            (3, "Maret"),
                            (4, "April"),
                            (5, "Mei"),
                            (6, "Juni"),
                            (7, "Juli"),
                            (8, "Agustus"),
                            (9, "September"),
                            (10, "Oktober"),
                            (11, "November"),
                            (12, "Desember"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "rencana_aksi",
                    models.TextField(
                        blank=True, null=True, verbose_name="Rencana Aksi"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "rhk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.rencanahasilkerja",
                        verbose_name="Rencana Hasil Kerja Pegawai",
                    ),
                ),
                (
                    "skp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                        verbose_name="Sasaran Kinerja Pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rencana Aksi",
                "verbose_name_plural": "Rencana Aksi",
            },
        ),
    ]
