# Generated by Django 4.1.2 on 2022-12-12 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0021_remove_buktidukung_rhk_remove_buktidukung_skp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hasil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nama Hasil"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "keterangan",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keterangan"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Hasil",
                "verbose_name_plural": "Hasil",
            },
        ),
        migrations.CreateModel(
            name="PenilaianBawahan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periode",
                    models.IntegerField(
                        choices=[
                            (1, "Januari"),
                            (2, "Februari"),
                            (3, "Maret"),
                            (4, "April"),
                            (5, "Mei"),
                            (6, "Juni"),
                            (7, "Juli"),
                            (8, "Agustus"),
                            (9, "September"),
                            (10, "Oktober"),
                            (11, "November"),
                            (12, "Desember"),
                        ],
                        null=True,
                    ),
                ),
                ("is_dinilai", models.BooleanField(default=False)),
                (
                    "predikat_kerja",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Predikat Kerja"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "predikat_perilaku",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hasil_predikat_perilaku_kerja",
                        to="skp.hasil",
                        verbose_name="Predikat Perilaku Kinerja",
                    ),
                ),
                (
                    "rating_hasil",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hasil_rating_kinerja",
                        to="skp.hasil",
                        verbose_name="Rating Hasil Kinerja",
                    ),
                ),
                (
                    "skp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                        verbose_name="Sasaran Kinerja Pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Penilaian Bawahan",
                "verbose_name_plural": "Penilaian Bawahan",
            },
        ),
    ]
