# Generated by Django 4.1.2 on 2022-12-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0026_initial_master_umpan_balik"),
    ]

    operations = [
        migrations.CreateModel(
            name="DaftarEkspetasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ekspetasi", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "perilaku_kerja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.perilakukerja",
                        verbose_name="Perilaku Kerja",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daftar Ekspetasi",
                "verbose_name_plural": "Daftar Ekspetasi",
            },
        ),
        migrations.AddField(
            model_name="daftarperilakukerjapegawai",
            name="ekspetasi_tambahan",
            field=models.ManyToManyField(blank=True, to="skp.daftarekspetasi"),
        ),
    ]
