# Generated by Django 4.1.2 on 2022-12-20 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0028_initial_master_daftar_ekspetasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmpanBalikPegawai",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "periode",
                    models.IntegerField(
                        choices=[
                            (1, "Januari"),
                            (2, "Februari"),
                            (3, "Maret"),
                            (4, "April"),
                            (5, "Mei"),
                            (6, "Juni"),
                            (7, "Juli"),
                            (8, "Agustus"),
                            (9, "September"),
                            (10, "Oktober"),
                            (11, "November"),
                            (12, "Desember"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "umpan_balik_tambahan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Umpan Balik Tambahan",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "indikator",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.indikatorkinerjaindividu",
                        verbose_name="Indikator Kerja Individu",
                    ),
                ),
                (
                    "umpan_balik",
                    models.ManyToManyField(blank=True, to="skp.umpanbalik"),
                ),
            ],
            options={
                "verbose_name": "Umpan Balik Tambahan",
                "verbose_name_plural": "Umpan Balik Tambahan",
            },
        ),
    ]
