# Generated by Django 4.1.2 on 2022-12-29 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0030_alter_penilaianbawahan_predikat_kerja"),
    ]

    operations = [
        migrations.CreateModel(
            name="RiwayatKeteranganSKP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keterangan",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Keterangan"
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "skp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                        verbose_name="Sasaran Kinerja Pegawai",
                    ),
                ),
            ],
            options={
                "verbose_name": "Riwayat Keterangan Sasaran Kinerja Pegawai",
                "verbose_name_plural": "Riwayat Keterangan Sasaran Kinerja Pegawai",
            },
        ),
    ]
