# Generated by Django 4.1.2 on 2023-01-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0032_lowercase_golongan"),
    ]

    operations = [
        migrations.AddField(
            model_name="detailsasarankinerja",
            name="status_pegawai",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Status Pegawai"
            ),
        ),
        migrations.AddField(
            model_name="detailsasarankinerja",
            name="status_pejabat",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Status Pejabat"
            ),
        ),
    ]
