# Generated by Django 4.1.2 on 2023-01-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skp", "0033_lowercase_golongan"),
    ]

    operations = [
        migrations.CreateModel(
            name="UmpanBalikPerilakuKerja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "umpan_balik_tambahan",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Umpan Balik Tambahan",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "perilaku_kerja",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.perilakukerja",
                        verbose_name="Perilaku Kerja",
                    ),
                ),
                (
                    "skp",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="skp.sasarankinerja",
                        verbose_name="Sasaran Kinerja Pegawai",
                    ),
                ),
                (
                    "umpan_balik",
                    models.ManyToManyField(blank=True, to="skp.umpanbalik"),
                ),
            ],
            options={
                "verbose_name": "Umpan Balik Perilaku Kerja",
                "verbose_name_plural": "Umpan Balik Perilaku Kerja",
            },
        ),
    ]
